language: go
go:
  - 1.7.3

script:
  - go test -v -tags=integration ./...

after_success:
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - ./coverage.bash
  - goveralls -coverprofile gover.coverprofile -service drone.io -repotoken $COVERALLS_TOKEN
